const ts=require('typescript');const fs=require('node:fs');const path=require('node:path');
module.exports=function extract(file, startText, endText, name, after=''){
 file=path.resolve(file);const source=fs.readFileSync(file,'utf8');const from=after?source.indexOf(after):0;if(from<0)throw Error('Missing function anchor '+after);const start=source.indexOf(startText,from);const endStart=source.indexOf(endText,start);if(start<0||endStart<0)throw Error('Missing extraction boundaries '+name);const range={pos:start,end:endStart+endText.length};
 const host={getScriptFileNames:()=>[file],getScriptVersion:()=> '1',getScriptSnapshot:f=>fs.existsSync(f)?ts.ScriptSnapshot.fromString(fs.readFileSync(f,'utf8')):undefined,getCurrentDirectory:()=>process.cwd(),getCompilationSettings:()=>({allowJs:true,noResolve:true,target:ts.ScriptTarget.ESNext}),getDefaultLibFileName:o=>ts.getDefaultLibFilePath(o),fileExists:ts.sys.fileExists,readFile:ts.sys.readFile,readDirectory:ts.sys.readDirectory};
 const service=ts.createLanguageService(host);const refactor=service.getApplicableRefactors(file,range,{allowTextChangesInNewFiles:true},'invoked').find(r=>r.name==='Extract Symbol');const action=refactor?.actions.filter(a=>a.name.startsWith('function_scope')).at(-1);if(!action)throw Error('Cannot extract '+name);
 const result=service.getEditsForRefactor(file,{indentSize:2,tabSize:2,convertTabsToSpaces:true,insertSpaceAfterCommaDelimiter:true,insertSpaceBeforeAndAfterBinaryOperators:true,insertSpaceAfterKeywordsInControlFlowStatements:true,insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces:true,newLineCharacter:'\n'},range,refactor.name,action.name,{});
 let changed=source;for(const e of result.edits){if(path.resolve(e.fileName)!==file)throw Error('Unexpected external edit');for(const c of e.textChanges.sort((a,b)=>b.span.start-a.span.start))changed=changed.slice(0,c.span.start)+c.newText.replace(/\bnewFunction\b/g,name)+changed.slice(c.span.start+c.span.length);}
 const errors=ts.createSourceFile(file,changed,ts.ScriptTarget.Latest,true).parseDiagnostics;if(errors.length)throw Error('Invalid generated code '+name);
 fs.writeFileSync(file,changed);service.dispose();console.log('Extracted',name);
};
